[package]
name = "cs395_project"
version = "0.0.2"
authors = ["Caleb Anderson <cande045@odu.edu>"]
edition = "2021"

[dependencies]


[dev-dependencies]
hamcrest2 = "*" 
stringreader = "0.1.1"
thiserror = "2.0.10"
eyre = "0.6.12"